// Code generated by protoc-gen-go. DO NOT EDIT.
// source: route.proto

package OpenNos_EthSwitch_L3_Mgmt

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RouteMgmtResult_Result int32

const (
	RouteMgmtResult_FAILED  RouteMgmtResult_Result = 0
	RouteMgmtResult_SUCCESS RouteMgmtResult_Result = 1
)

var RouteMgmtResult_Result_name = map[int32]string{
	0: "FAILED",
	1: "SUCCESS",
}

var RouteMgmtResult_Result_value = map[string]int32{
	"FAILED":  0,
	"SUCCESS": 1,
}

func (x RouteMgmtResult_Result) String() string {
	return proto.EnumName(RouteMgmtResult_Result_name, int32(x))
}

func (RouteMgmtResult_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{4, 0}
}

type Network4 struct {
	Cidr4                string   `protobuf:"bytes,1,opt,name=cidr4,proto3" json:"cidr4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Network4) Reset()         { *m = Network4{} }
func (m *Network4) String() string { return proto.CompactTextString(m) }
func (*Network4) ProtoMessage()    {}
func (*Network4) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{0}
}

func (m *Network4) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Network4.Unmarshal(m, b)
}
func (m *Network4) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Network4.Marshal(b, m, deterministic)
}
func (m *Network4) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Network4.Merge(m, src)
}
func (m *Network4) XXX_Size() int {
	return xxx_messageInfo_Network4.Size(m)
}
func (m *Network4) XXX_DiscardUnknown() {
	xxx_messageInfo_Network4.DiscardUnknown(m)
}

var xxx_messageInfo_Network4 proto.InternalMessageInfo

func (m *Network4) GetCidr4() string {
	if m != nil {
		return m.Cidr4
	}
	return ""
}

type NextHop4 struct {
	Ip4                  string   `protobuf:"bytes,1,opt,name=ip4,proto3" json:"ip4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextHop4) Reset()         { *m = NextHop4{} }
func (m *NextHop4) String() string { return proto.CompactTextString(m) }
func (*NextHop4) ProtoMessage()    {}
func (*NextHop4) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{1}
}

func (m *NextHop4) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextHop4.Unmarshal(m, b)
}
func (m *NextHop4) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextHop4.Marshal(b, m, deterministic)
}
func (m *NextHop4) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextHop4.Merge(m, src)
}
func (m *NextHop4) XXX_Size() int {
	return xxx_messageInfo_NextHop4.Size(m)
}
func (m *NextHop4) XXX_DiscardUnknown() {
	xxx_messageInfo_NextHop4.DiscardUnknown(m)
}

var xxx_messageInfo_NextHop4 proto.InternalMessageInfo

func (m *NextHop4) GetIp4() string {
	if m != nil {
		return m.Ip4
	}
	return ""
}

type AddRoute4Request struct {
	Network              *Network4 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	NextHop              *NextHop4 `protobuf:"bytes,2,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddRoute4Request) Reset()         { *m = AddRoute4Request{} }
func (m *AddRoute4Request) String() string { return proto.CompactTextString(m) }
func (*AddRoute4Request) ProtoMessage()    {}
func (*AddRoute4Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{2}
}

func (m *AddRoute4Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRoute4Request.Unmarshal(m, b)
}
func (m *AddRoute4Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRoute4Request.Marshal(b, m, deterministic)
}
func (m *AddRoute4Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRoute4Request.Merge(m, src)
}
func (m *AddRoute4Request) XXX_Size() int {
	return xxx_messageInfo_AddRoute4Request.Size(m)
}
func (m *AddRoute4Request) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRoute4Request.DiscardUnknown(m)
}

var xxx_messageInfo_AddRoute4Request proto.InternalMessageInfo

func (m *AddRoute4Request) GetNetwork() *Network4 {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *AddRoute4Request) GetNextHop() *NextHop4 {
	if m != nil {
		return m.NextHop
	}
	return nil
}

type WithdrawRoute4Request struct {
	Network              *Network4 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *WithdrawRoute4Request) Reset()         { *m = WithdrawRoute4Request{} }
func (m *WithdrawRoute4Request) String() string { return proto.CompactTextString(m) }
func (*WithdrawRoute4Request) ProtoMessage()    {}
func (*WithdrawRoute4Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{3}
}

func (m *WithdrawRoute4Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRoute4Request.Unmarshal(m, b)
}
func (m *WithdrawRoute4Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRoute4Request.Marshal(b, m, deterministic)
}
func (m *WithdrawRoute4Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRoute4Request.Merge(m, src)
}
func (m *WithdrawRoute4Request) XXX_Size() int {
	return xxx_messageInfo_WithdrawRoute4Request.Size(m)
}
func (m *WithdrawRoute4Request) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRoute4Request.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRoute4Request proto.InternalMessageInfo

func (m *WithdrawRoute4Request) GetNetwork() *Network4 {
	if m != nil {
		return m.Network
	}
	return nil
}

type RouteMgmtResult struct {
	Result               RouteMgmtResult_Result `protobuf:"varint,1,opt,name=result,proto3,enum=OpenNos.EthSwitch.L3.Mgmt.RouteMgmtResult_Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RouteMgmtResult) Reset()         { *m = RouteMgmtResult{} }
func (m *RouteMgmtResult) String() string { return proto.CompactTextString(m) }
func (*RouteMgmtResult) ProtoMessage()    {}
func (*RouteMgmtResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{4}
}

func (m *RouteMgmtResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteMgmtResult.Unmarshal(m, b)
}
func (m *RouteMgmtResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteMgmtResult.Marshal(b, m, deterministic)
}
func (m *RouteMgmtResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteMgmtResult.Merge(m, src)
}
func (m *RouteMgmtResult) XXX_Size() int {
	return xxx_messageInfo_RouteMgmtResult.Size(m)
}
func (m *RouteMgmtResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteMgmtResult.DiscardUnknown(m)
}

var xxx_messageInfo_RouteMgmtResult proto.InternalMessageInfo

func (m *RouteMgmtResult) GetResult() RouteMgmtResult_Result {
	if m != nil {
		return m.Result
	}
	return RouteMgmtResult_FAILED
}

func init() {
	proto.RegisterEnum("OpenNos.EthSwitch.L3.Mgmt.RouteMgmtResult_Result", RouteMgmtResult_Result_name, RouteMgmtResult_Result_value)
	proto.RegisterType((*Network4)(nil), "OpenNos.EthSwitch.L3.Mgmt.Network4")
	proto.RegisterType((*NextHop4)(nil), "OpenNos.EthSwitch.L3.Mgmt.NextHop4")
	proto.RegisterType((*AddRoute4Request)(nil), "OpenNos.EthSwitch.L3.Mgmt.AddRoute4Request")
	proto.RegisterType((*WithdrawRoute4Request)(nil), "OpenNos.EthSwitch.L3.Mgmt.WithdrawRoute4Request")
	proto.RegisterType((*RouteMgmtResult)(nil), "OpenNos.EthSwitch.L3.Mgmt.RouteMgmtResult")
}

func init() { proto.RegisterFile("route.proto", fileDescriptor_0984d49a362b6b9f) }

var fileDescriptor_0984d49a362b6b9f = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xca, 0x2f, 0x2d,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0xf4, 0x2f, 0x48, 0xcd, 0xf3, 0xcb, 0x2f,
	0xd6, 0x73, 0x2d, 0xc9, 0x08, 0x2e, 0xcf, 0x2c, 0x49, 0xce, 0xd0, 0xf3, 0x31, 0xd6, 0xf3, 0x4d,
	0xcf, 0x2d, 0x51, 0x52, 0xe0, 0xe2, 0xf0, 0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca, 0x36, 0x11, 0x12,
	0xe1, 0x62, 0x4d, 0xce, 0x4c, 0x29, 0x32, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70,
	0x94, 0x64, 0x40, 0x2a, 0x2a, 0x4a, 0x3c, 0xf2, 0x0b, 0x4c, 0x84, 0x04, 0xb8, 0x98, 0x33, 0x0b,
	0x60, 0xf2, 0x20, 0xa6, 0xd2, 0x44, 0x46, 0x2e, 0x01, 0xc7, 0x94, 0x94, 0x20, 0x90, 0x6d, 0x26,
	0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xb6, 0x5c, 0xec, 0x79, 0x10, 0x43, 0xc1, 0x4a,
	0xb9, 0x8d, 0x94, 0xf5, 0x70, 0xba, 0x40, 0x0f, 0x66, 0x7d, 0x10, 0x4c, 0x8f, 0x90, 0x1d, 0x17,
	0x47, 0x5e, 0x6a, 0x45, 0x49, 0x7c, 0x46, 0x7e, 0x81, 0x04, 0x13, 0x11, 0xfa, 0x21, 0x8e, 0x03,
	0xe9, 0x07, 0xb3, 0x94, 0xc2, 0xb8, 0x44, 0xc3, 0x33, 0x4b, 0x32, 0x52, 0x8a, 0x12, 0xcb, 0xa9,
	0xe9, 0x2e, 0xa5, 0x7a, 0x2e, 0x7e, 0xb0, 0x79, 0x20, 0xe9, 0xa0, 0xd4, 0xe2, 0xd2, 0x9c, 0x12,
	0x21, 0x4f, 0x2e, 0xb6, 0x22, 0x30, 0x0b, 0x6c, 0x20, 0x9f, 0x91, 0x21, 0x1e, 0x03, 0xd1, 0xf4,
	0xea, 0x41, 0xa8, 0x20, 0xa8, 0x01, 0x4a, 0x8a, 0x5c, 0x6c, 0x50, 0x43, 0xb9, 0xb8, 0xd8, 0xdc,
	0x1c, 0x3d, 0x7d, 0x5c, 0x5d, 0x04, 0x18, 0x84, 0xb8, 0xb9, 0xd8, 0x83, 0x43, 0x9d, 0x9d, 0x5d,
	0x83, 0x83, 0x05, 0x18, 0x8d, 0x9e, 0x32, 0x72, 0x71, 0xc2, 0x4d, 0x11, 0x4a, 0xe3, 0xe2, 0x84,
	0x87, 0xbc, 0x90, 0x36, 0x1e, 0x8b, 0xd1, 0xe3, 0x47, 0x4a, 0x8b, 0x78, 0x57, 0x2a, 0x31, 0x08,
	0x15, 0x70, 0xf1, 0xa1, 0x06, 0xa7, 0x90, 0x01, 0x1e, 0xfd, 0x58, 0x43, 0x9e, 0x34, 0x1b, 0x93,
	0xd8, 0xc0, 0xc9, 0xd6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xf1, 0x98, 0xef, 0xc5, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RouteMgmtClient is the client API for RouteMgmt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouteMgmtClient interface {
	AddRoute4(ctx context.Context, in *AddRoute4Request, opts ...grpc.CallOption) (*RouteMgmtResult, error)
	WithdrawRoute4(ctx context.Context, in *WithdrawRoute4Request, opts ...grpc.CallOption) (*RouteMgmtResult, error)
}

type routeMgmtClient struct {
	cc grpc.ClientConnInterface
}

func NewRouteMgmtClient(cc grpc.ClientConnInterface) RouteMgmtClient {
	return &routeMgmtClient{cc}
}

func (c *routeMgmtClient) AddRoute4(ctx context.Context, in *AddRoute4Request, opts ...grpc.CallOption) (*RouteMgmtResult, error) {
	out := new(RouteMgmtResult)
	err := c.cc.Invoke(ctx, "/OpenNos.EthSwitch.L3.Mgmt.RouteMgmt/AddRoute4", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeMgmtClient) WithdrawRoute4(ctx context.Context, in *WithdrawRoute4Request, opts ...grpc.CallOption) (*RouteMgmtResult, error) {
	out := new(RouteMgmtResult)
	err := c.cc.Invoke(ctx, "/OpenNos.EthSwitch.L3.Mgmt.RouteMgmt/WithdrawRoute4", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouteMgmtServer is the server API for RouteMgmt service.
type RouteMgmtServer interface {
	AddRoute4(context.Context, *AddRoute4Request) (*RouteMgmtResult, error)
	WithdrawRoute4(context.Context, *WithdrawRoute4Request) (*RouteMgmtResult, error)
}

// UnimplementedRouteMgmtServer can be embedded to have forward compatible implementations.
type UnimplementedRouteMgmtServer struct {
}

func (*UnimplementedRouteMgmtServer) AddRoute4(ctx context.Context, req *AddRoute4Request) (*RouteMgmtResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRoute4 not implemented")
}
func (*UnimplementedRouteMgmtServer) WithdrawRoute4(ctx context.Context, req *WithdrawRoute4Request) (*RouteMgmtResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawRoute4 not implemented")
}

func RegisterRouteMgmtServer(s *grpc.Server, srv RouteMgmtServer) {
	s.RegisterService(&_RouteMgmt_serviceDesc, srv)
}

func _RouteMgmt_AddRoute4_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoute4Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteMgmtServer).AddRoute4(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpenNos.EthSwitch.L3.Mgmt.RouteMgmt/AddRoute4",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteMgmtServer).AddRoute4(ctx, req.(*AddRoute4Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteMgmt_WithdrawRoute4_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRoute4Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteMgmtServer).WithdrawRoute4(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OpenNos.EthSwitch.L3.Mgmt.RouteMgmt/WithdrawRoute4",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteMgmtServer).WithdrawRoute4(ctx, req.(*WithdrawRoute4Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _RouteMgmt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OpenNos.EthSwitch.L3.Mgmt.RouteMgmt",
	HandlerType: (*RouteMgmtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRoute4",
			Handler:    _RouteMgmt_AddRoute4_Handler,
		},
		{
			MethodName: "WithdrawRoute4",
			Handler:    _RouteMgmt_WithdrawRoute4_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "route.proto",
}
